services:
    steveurkel.incognito.listener:
        class: steveurkel\incognito\event\post_listener
        arguments:
            - @config
            - @template
            - @user
            - @request
            - @auth
        tags:
            - { name: event.listener }